server:
  port: 8084
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gmall_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
#  redis:
#    host: 172.16.116.100
mybatis-plus:
  mapper-locations: classpath:mapper/oms/*.xml  # \u8BFB\u53D6\u6620\u5C04\u6587\u4EF6
  global-config:
    db-config:
      id-type: auto  # \u9ED8\u8BA4\u4F7F\u7528\u6570\u636E\u5E93\u81EA\u589E
